# 开发环境配置
server:
  # 服务端口
  port: 80
  servlet:
    # 项目contextPath
    context-path: /linzx
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  application:
    name: web-example
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
  profiles:
    active: prod
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 6
      master:
        url: jdbc:mysql://139.196.72.210:3306/web_example?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      slave:
        enabled: false
        url: jdbc:mysql://139.196.72.210:3306/web_example?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: 123456
      statViewServlet:
        enabled: true
        url-pattern: /monitor/druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

# PageHelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  # 设置为 true 时，如果 pageSize=0 就会查询出全部的结果
  page-size-zero: true

# mybatis配置
mybatis:
  # 加载全局的配置文件
  config-location: classpath:config/mybatis-config.xml
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath*:mapper/**/*Mapper.xml

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /login
  cache:
    module-name: system
    # 登录认证realm缓存
    authentication: userRealm

# 上传相关配置
upload:
  base:
    path: /usr/upload
  aliyun:
    oss:
      bucketname: web-example
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI4FgjDiwMaeXyMcTkEXFc
      keysecret: gKH9vBK6BnweQ03NMzGugdYunQ20wj
rocketmq:
  group-name: ${spring.application.name}
  namesrv-addr: 139.196.72.210:9876
  producer:
    enable: true
    vip-channel-enabled: false
    retry-times-when-send-async-failed: 3
  consumer:
    enable: true